# Generated by Django 3.1.3 on 2022-03-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_answer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
