# Generated by Django 3.1.3 on 2022-03-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0008_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
