# Generated by Django 3.1.3 on 2022-03-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_auto_20220308_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='modified_date',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modified_date',
            new_name='modify_date',
        ),
    ]
