# Generated by Django 3.1.3 on 2022-05-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0013_auto_20220312_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='n_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
