# Generated by Django 3.1.3 on 2022-05-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0014_question_n_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='n_hit',
        ),
        migrations.AddField(
            model_name='question',
            name='hit',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
