# Generated by Django 3.1.3 on 2022-05-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0015_auto_20220525_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hit',
        ),
    ]
