# Generated by Django 3.1.3 on 2022-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0017_questioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
