# Generated by Django 3.1.3 on 2022-05-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0018_question_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
